/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("me.stasiak.flagship.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":deployment-unit:example-module:application"))
    implementation(project(":deployment-unit:example-module:examples"))
}

application {
    // Define the main class for the application.
    mainClass.set("me.stasiak.flagship.app.AppKt")
}
