/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("application-conventions")
    id("ktor-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")

    // elements order matters
    implementation(project(":deployment-unit:common:errors"))
    implementation(project(":deployment-unit:common:ktor"))

//    implementation(project(":deployment-unit:user-module:domain"))
//    implementation(project(":deployment-unit:user-module:application"))

    implementation(project(":deployment-unit:user-module:interfaces-ktor"))

    implementation(project(":deployment-unit:article-module:interfaces-ktor"))

    implementation(project(":deployment-unit:profile-module:interfaces-ktor"))

    implementation(project(":deployment-unit:examples"))
}

application {
    // Define the main class for the application.
    mainClass.set("me.stasiak.flagship.app.AppKt")
}
