/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("application-conventions")
    id("ktor-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")

    implementation(project(":deployment-unit:user-module:application"))
    implementation(project(":deployment-unit:user-module:interfaces"))
    implementation(project(":deployment-unit:user-module:domain"))

    implementation(project(":deployment-unit:examples"))
}

application {
    // Define the main class for the application.
    mainClass.set("me.stasiak.flagship.app.AppKt")
}
