/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("library-conventions")
    id("postgres-conventions")
}

dependencies {
    api(project(":deployment-unit:user-module:domain"))
}
