/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package me.stasiak.flagship.app

import me.stasiak.flagship.application.contextReceiversExample


fun main() {
//    val tokens = StringUtils.split(MessageUtils.getMessage())
//    val result = StringUtils.join(tokens)
//    println(WordUtils.capitalize(result))
    contextReceiversExample()
}
